// RVA 0x25F3A8, .rdata
// Symbol: ??_7?$CSharedResourceMarshaler@VCLegacyAnimationTriggerMarshaler@DirectComposition@@$01@DirectComposition@@6B@
void *___7__CSharedResourceMarshaler_VCLegacyAnimationTriggerMarshaler_DirectComposition___01_DirectComposition__6B_ = reinterpret_cast<decltype(___7__CSharedResourceMarshaler_VCLegacyAnimationTriggerMarshaler_DirectComposition___01_DirectComposition__6B_)>(0x00000001401491F0); // 5370057200
