// RVA 0x50EB18, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxunrmrlUhvxfirgbUorxvmhrmtUhkxzooUoryUyfrowPhvieviPpnUlyquivUznwGEUhgwzucOlyq@spcall_server_km
unsigned char _____PchSym__00_KxulyqvxgPillgKxunrmrlUhvxfirgbUorxvmhrmtUhkxzooUoryUyfrowPhvieviPpnUlyquivUznwGEUhgwzucOlyq_spcall_server_km = 0x00; // 0
