// RVA 0x542C0, .rdata
// Symbol: ??_7DMMVIDPNTARGETMODESET@@6B?$SignedWithClassSignature@VDMMVIDPNTARGETMODESET@@@@@
void *___7DMMVIDPNTARGETMODESET__6B__SignedWithClassSignature_VDMMVIDPNTARGETMODESET_____ = reinterpret_cast<decltype(___7DMMVIDPNTARGETMODESET__6B__SignedWithClassSignature_VDMMVIDPNTARGETMODESET_____)>(0x00000001C001CC00); // 7516310528
