// RVA 0x55AF0, .rdata
// Symbol: ??_7DMMVIDEOPRESENTTARGET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTTARGET@@@@@
void *___7DMMVIDEOPRESENTTARGET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTTARGET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGET_____)>(0x00000001C001CC20); // 7516310560
