// RVA 0x6FC40, .rdata
// Symbol: ??_7DMMVIDEOPRESENTTARGET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTTARGET@@@@@
void *___7DMMVIDEOPRESENTTARGET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTTARGET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGET_____)>(0x00000001C0026AB0); // 7516351152
