// RVA 0x6F5D8, .rdata
// Symbol: ??_7DMMVIDPNSOURCEMODESET@@6B?$SignedWithClassSignature@VDMMVIDPNSOURCEMODESET@@@@@
void *___7DMMVIDPNSOURCEMODESET__6B__SignedWithClassSignature_VDMMVIDPNSOURCEMODESET_____ = reinterpret_cast<decltype(___7DMMVIDPNSOURCEMODESET__6B__SignedWithClassSignature_VDMMVIDPNSOURCEMODESET_____)>(0x00000001C0026B00); // 7516351232
