// RVA 0x6F850, .rdata
// Symbol: ??_7DISPMODECHANGEREQUEST@VIDPN_MGR@@6B?$SignedWithClassSignature@UDISPMODECHANGEREQUEST@VIDPN_MGR@@@@@
void *___7DISPMODECHANGEREQUEST_VIDPN_MGR__6B__SignedWithClassSignature_UDISPMODECHANGEREQUEST_VIDPN_MGR_____ = reinterpret_cast<decltype(___7DISPMODECHANGEREQUEST_VIDPN_MGR__6B__SignedWithClassSignature_UDISPMODECHANGEREQUEST_VIDPN_MGR_____)>(0x00000001C00269A0); // 7516350880
