// RVA 0xAEBC0, .data
// Symbol: ?_MonitorConfigInfoTable@DXGMONITOR@@0PAU_MONTIOR_CONFIG_TABLE@1@A
struct DXGMONITOR::_MONTIOR_CONFIG_TABLE near *__MonitorConfigInfoTable_DXGMONITOR__0PAU_MONTIOR_CONFIG_TABLE_1_A = reinterpret_cast<decltype(__MonitorConfigInfoTable_DXGMONITOR__0PAU_MONTIOR_CONFIG_TABLE_1_A)>(0x00000001C007A600); // 7516694016
