// RVA 0x18F860, .data
// Symbol: ?gWakeInProgressReason@@3W4POWER_MONITOR_REQUEST_REASON@@A
enum POWER_MONITOR_REQUEST_REASON _gWakeInProgressReason__3W4POWER_MONITOR_REQUEST_REASON__A = 0x00000000; // 0
