// RVA 0x172770, .rdata
// Symbol: ?Methods@?$IMagnifierServerPrincipal_Receive@VBamoMagnifierServerPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IMagnifierServerPrincipal_Receive_VBamoMagnifierServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IMagnifierServerPrincipal_Receive_VBamoMagnifierServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180070280); // 6442910336
