// RVA 0x172250, .rdata
// Symbol: ?Methods@?$IAttachableInputObjectSampleProxy_Receive@VBamoAttachableInputObjectSampleProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IAttachableInputObjectSampleProxy_Receive_VBamoAttachableInputObjectSampleProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IAttachableInputObjectSampleProxy_Receive_VBamoAttachableInputObjectSampleProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180062F60); // 6442856288
