// RVA 0x1E18C0, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgslhgUxlnklmvmghUfrzsrggvhgUhvieviUlyquivUznwGEUkxsOlyq@UIAHitTestServer
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgslhgUxlnklmvmghUfrzsrggvhgUhvieviUlyquivUznwGEUkxsOlyq_UIAHitTestServer = 0x00; // 0
