// RVA 0x80950, .data
// Symbol: ?m_pPhysicalPool@VIDMM_GLOBAL@@0PEAVVIDMM_LINEAR_POOL@@EA
VIDMM_LINEAR_POOL *_m_pPhysicalPool_VIDMM_GLOBAL__0PEAVVIDMM_LINEAR_POOL__EA = reinterpret_cast<decltype(_m_pPhysicalPool_VIDMM_GLOBAL__0PEAVVIDMM_LINEAR_POOL__EA)>(0x0000000000000000); // 0
