// RVA 0x80140, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwctnnhCUxlivUlyquivUznwGEUkivxlnkOlyq@dxgmms2
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwctnnhCUxlivUlyquivUznwGEUkivxlnkOlyq_dxgmms2 = 0x00; // 0
