// RVA 0x2E1B0, .rdata
// Symbol: ??_7DMMVIDEOPRESENTTARGETSET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTTARGETSET@@@@@
void *___7DMMVIDEOPRESENTTARGETSET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGETSET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTTARGETSET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGETSET_____)>(0x00000001C0010EC0); // 7516262080
