// RVA 0x2E4F8, .rdata
// Symbol: ??_7DMMVIDEOPRESENTSOURCE@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTSOURCE@@@@@
void *___7DMMVIDEOPRESENTSOURCE__6B__SignedWithClassSignature_VDMMVIDEOPRESENTSOURCE_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTSOURCE__6B__SignedWithClassSignature_VDMMVIDEOPRESENTSOURCE_____)>(0x00000001C00111B0); // 7516262832
