// RVA 0x2E630, .rdata
// Symbol: ??_7COMMITVIDPNREQUEST@VIDPN_MGR@@6B?$SignedWithClassSignature@UCOMMITVIDPNREQUEST@VIDPN_MGR@@@@@
void *___7COMMITVIDPNREQUEST_VIDPN_MGR__6B__SignedWithClassSignature_UCOMMITVIDPNREQUEST_VIDPN_MGR_____ = reinterpret_cast<decltype(___7COMMITVIDPNREQUEST_VIDPN_MGR__6B__SignedWithClassSignature_UCOMMITVIDPNREQUEST_VIDPN_MGR_____)>(0x00000001C0010E90); // 7516262032
