// RVA 0x2E310, .rdata
// Symbol: ??_7DMMVIDPNSOURCEMODESET@@6B?$SignedWithClassSignature@VDMMVIDPNSOURCEMODESET@@@@@
void *___7DMMVIDPNSOURCEMODESET__6B__SignedWithClassSignature_VDMMVIDPNSOURCEMODESET_____ = reinterpret_cast<decltype(___7DMMVIDPNSOURCEMODESET__6B__SignedWithClassSignature_VDMMVIDPNSOURCEMODESET_____)>(0x00000001C0010FF0); // 7516262384
