// RVA 0x2F190, .rdata
// Symbol: ?FlagsDefault@DXGSYNCOBJECT@@0U_D3DDDI_SYNCHRONIZATIONOBJECT_FLAGS@@B
// Type: const struct _D3DDDI_SYNCHRONIZATIONOBJECT_FLAGS
unsigned char _FlagsDefault_DXGSYNCOBJECT__0U_D3DDDI_SYNCHRONIZATIONOBJECT_FLAGS__B[0x4] = {};
