// RVA 0x25865C, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUmgfhviUpvimvoUrmkfgUkgkUpnUlyquivUznwGEUkivxlnkOlyq@ptpEngine
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUmgfhviUpvimvoUrmkfgUkgkUpnUlyquivUznwGEUkivxlnkOlyq_ptpEngine = 0x00; // 0
