// RVA 0x31EC90, .data
// Symbol: ?gapfnStrip@@3PAP6AXPEAU_STRIP@@PEAU_BMINFO@@PEAU_LINESTATE@@@ZA
void (* near *_gapfnStrip__3PAP6AXPEAU_STRIP__PEAU_BMINFO__PEAU_LINESTATE___ZA)(struct _STRIP *, struct _BMINFO *, struct _LINESTATE *) = reinterpret_cast<decltype(_gapfnStrip__3PAP6AXPEAU_STRIP__PEAU_BMINFO__PEAU_LINESTATE___ZA)>(0x00000001C013E440); // 7517496384
