// RVA 0x23C548, .rdata
// Symbol: ?apfnRead@@3QAY02Q6GPAU_XRUNLEN@@PAU_STRDDA@@PAU_STRRUN@@PAE2PAU_XLATEOBJ@@JJJ@ZA
unsigned char _apfnRead__3QAY02Q6GPAU_XRUNLEN__PAU_STRDDA__PAU_STRRUN__PAE2PAU_XLATEOBJ__JJJ_ZA = 0x00; // 0
