// RVA 0x2655A8, .data
// Symbol: ?gpfmffTable@@3PAU_FONTMAPPERFAMILYFALLBACK@@A
struct _FONTMAPPERFAMILYFALLBACK *_gpfmffTable__3PAU_FONTMAPPERFAMILYFALLBACK__A = reinterpret_cast<decltype(_gpfmffTable__3PAU_FONTMAPPERFAMILYFALLBACK__A)>(0x00000000); // 0
