// RVA 0x124108, .data
// Symbol: ___@@_PchSym_@00@KxulyqvxgPillgKxunrmpvimvoUzkkxlnkzgUhdrgxsyzxpUxlmgvcgUolzwviUlyquivUrDIGUkivxlnkOlyq@SwitchContextLoader
unsigned char ______PchSym__00_KxulyqvxgPillgKxunrmpvimvoUzkkxlnkzgUhdrgxsyzxpUxlmgvcgUolzwviUlyquivUrDIGUkivxlnkOlyq_SwitchContextLoader = 0x00; // 0
