// RVA 0x128A48, .data
// Symbol: ___@@_PchSym_@00@KxulyqvxgPillgKxunrmpvimvoUzkkxlnkzgUxzxsvUrmgviuzxvUorynrmUlyquivUrDIGUxlnkzgxzxsvkOlyq@compatcachemin
unsigned char ______PchSym__00_KxulyqvxgPillgKxunrmpvimvoUzkkxlnkzgUxzxsvUrmgviuzxvUorynrmUlyquivUrDIGUxlnkzgxzxsvkOlyq_compatcachemin = 0x00; // 0
