// RVA 0x2574A8, .rdata
// Symbol: ??_7?$CSharedResourceMarshaler@VCCompositionAmbientLightMarshaler@DirectComposition@@$01@DirectComposition@@6B@
void *___7__CSharedResourceMarshaler_VCCompositionAmbientLightMarshaler_DirectComposition___01_DirectComposition__6B_ = reinterpret_cast<decltype(___7__CSharedResourceMarshaler_VCCompositionAmbientLightMarshaler_DirectComposition___01_DirectComposition__6B_)>(0x000000014014A080); // 5370060928
