// RVA 0x71310, .rdata
// Symbol: ?VmBusCommandTableVmToHostCblt@DXG_HOST_GLOBAL_VMBUS@@2QBUDXG_VMBUS_COMMAND_TABLE@@B
const struct DXG_VMBUS_COMMAND_TABLE near *const _VmBusCommandTableVmToHostCblt_DXG_HOST_GLOBAL_VMBUS__2QBUDXG_VMBUS_COMMAND_TABLE__B = reinterpret_cast<decltype(_VmBusCommandTableVmToHostCblt_DXG_HOST_GLOBAL_VMBUS__2QBUDXG_VMBUS_COMMAND_TABLE__B)>(0x00000001C00D69C0); // 7517071808
