// RVA 0x5FC78, .rdata
// Symbol: ??_7?$DoublyLinkedList@VCONTEXT_DATA@ContextDataAssignee@@U?$DoubleLinkedListElementDeleter@VCONTEXT_DATA@ContextDataAssignee@@@@@@6B@
void *___7__DoublyLinkedList_VCONTEXT_DATA_ContextDataAssignee__U__DoubleLinkedListElementDeleter_VCONTEXT_DATA_ContextDataAssignee______6B_ = reinterpret_cast<decltype(___7__DoublyLinkedList_VCONTEXT_DATA_ContextDataAssignee__U__DoubleLinkedListElementDeleter_VCONTEXT_DATA_ContextDataAssignee______6B_)>(0x00000001C0017EB0); // 7516290736
