// RVA 0xA3550, .rdata
// Symbol: ??_7DMMVIDPNSOURCEMODESET@@6B?$SignedWithClassSignature@VDMMVIDPNSOURCEMODESET@@@@@
void *___7DMMVIDPNSOURCEMODESET__6B__SignedWithClassSignature_VDMMVIDPNSOURCEMODESET_____ = reinterpret_cast<decltype(___7DMMVIDPNSOURCEMODESET__6B__SignedWithClassSignature_VDMMVIDPNSOURCEMODESET_____)>(0x000000014008EBE0); // 5369293792
