// RVA 0xA34F0, .rdata
// Symbol: ??_7DMMVIDPNTARGETMODESET@@6B?$SignedWithClassSignature@VDMMVIDPNTARGETMODESET@@@@@
void *___7DMMVIDPNTARGETMODESET__6B__SignedWithClassSignature_VDMMVIDPNTARGETMODESET_____ = reinterpret_cast<decltype(___7DMMVIDPNTARGETMODESET__6B__SignedWithClassSignature_VDMMVIDPNTARGETMODESET_____)>(0x000000014008EC20); // 5369293856
