// RVA 0xA54C8, .rdata
// Symbol: ??_7DMMVIDEOPRESENTTARGETSET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTTARGETSET@@@@@
void *___7DMMVIDEOPRESENTTARGETSET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGETSET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTTARGETSET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGETSET_____)>(0x000000014008D3F0); // 5369287664
