// RVA 0xA4BD8, .rdata
// Symbol: ??_7DMMVIDEOPRESENTTARGET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTTARGET@@@@@
void *___7DMMVIDEOPRESENTTARGET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTTARGET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGET_____)>(0x000000014008E230); // 5369291312
