// RVA 0xA5500, .rdata
// Symbol: ??_7DMMVIDEOPRESENTSOURCESET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTSOURCESET@@@@@
void *___7DMMVIDEOPRESENTSOURCESET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTSOURCESET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTSOURCESET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTSOURCESET_____)>(0x000000014008D3C0); // 5369287616
