// RVA 0xA5528, .rdata
// Symbol: ??_7?$DoublyLinkedList@VCONTEXT_DATA@ContextDataAssignee@@U?$DoubleLinkedListElementDeleter@VCONTEXT_DATA@ContextDataAssignee@@@@@@6B@
void *___7__DoublyLinkedList_VCONTEXT_DATA_ContextDataAssignee__U__DoubleLinkedListElementDeleter_VCONTEXT_DATA_ContextDataAssignee______6B_ = reinterpret_cast<decltype(___7__DoublyLinkedList_VCONTEXT_DATA_ContextDataAssignee__U__DoubleLinkedListElementDeleter_VCONTEXT_DATA_ContextDataAssignee______6B_)>(0x000000014004D430); // 5369025584
