// RVA 0x859C8, .rdata
// Symbol: ??_7DMMVIDPNTARGETMODESET@@6B?$SignedWithClassSignature@VDMMVIDPNTARGETMODESET@@@@@
void *___7DMMVIDPNTARGETMODESET__6B__SignedWithClassSignature_VDMMVIDPNTARGETMODESET_____ = reinterpret_cast<decltype(___7DMMVIDPNTARGETMODESET__6B__SignedWithClassSignature_VDMMVIDPNTARGETMODESET_____)>(0x00000001C002D3E0); // 7516378080
