// RVA 0x1322F4, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwlwkivhvmgUlyquivUznwGEUkivxlnkOlyq@dodpresent
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwlwkivhvmgUlyquivUznwGEUkivxlnkOlyq_dodpresent = 0x00; // 0
