// RVA 0x2123D0, .data
// Symbol: ?gpfnHidP_GetCaps@@3P6AJPEAU_HIDP_PREPARSED_DATA@@PEAU_HIDP_CAPS@@@ZEA
int (*_gpfnHidP_GetCaps__3P6AJPEAU_HIDP_PREPARSED_DATA__PEAU_HIDP_CAPS___ZEA)(struct _HIDP_PREPARSED_DATA *, struct _HIDP_CAPS *) = reinterpret_cast<decltype(_gpfnHidP_GetCaps__3P6AJPEAU_HIDP_PREPARSED_DATA__PEAU_HIDP_CAPS___ZEA)>(0x0000000000000000); // 0
