// RVA 0x1B0A20, .rdata
// Symbol: ??_7FinalizeControllerInitialization@SpatialInteractionTrace@SpatialInteractionDevices@@6B@
void *___7FinalizeControllerInitialization_SpatialInteractionTrace_SpatialInteractionDevices__6B_ = reinterpret_cast<decltype(___7FinalizeControllerInitialization_SpatialInteractionTrace_SpatialInteractionDevices__6B_)>(0x00000001800D0290); // 6443303568
