// RVA 0x1B3250, .rdata
// Symbol: ??_7?$RuntimeClass@UIHomeGestureEventArgs@MPCManager@Input@Internal@Windows@@VFtmBase@WRL@Microsoft@@@WRL@Microsoft@@6BIWeakReferenceSource@@@
void *___7__RuntimeClass_UIHomeGestureEventArgs_MPCManager_Input_Internal_Windows__VFtmBase_WRL_Microsoft___WRL_Microsoft__6BIWeakReferenceSource___ = reinterpret_cast<decltype(___7__RuntimeClass_UIHomeGestureEventArgs_MPCManager_Input_Internal_Windows__VFtmBase_WRL_Microsoft___WRL_Microsoft__6BIWeakReferenceSource___)>(0x000000018004B7D0); // 6442760144
