// RVA 0x1AEF30, .rdata
// Symbol: ?Methods@?$IMPCManagerClientPrincipal_Receive@VBamoMPCManagerClientPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IMPCManagerClientPrincipal_Receive_VBamoMPCManagerClientPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IMPCManagerClientPrincipal_Receive_VBamoMPCManagerClientPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x00000001800468C0); // 6442739904
