// RVA 0x1AE8E0, .rdata
// Symbol: ?Methods@?$IBamoPeer_MPCManagerBamo_AutoBamos_Receive@VBamoPeerImpl@MPCManagerBamo_AutoBamos@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
_UNKNOWN *_Methods___IBamoPeer_MPCManagerBamo_AutoBamos_Receive_VBamoPeerImpl_MPCManagerBamo_AutoBamos_BamoImpl____2QBUMsgCallMethodDefinition__B = reinterpret_cast<decltype(_Methods___IBamoPeer_MPCManagerBamo_AutoBamos_Receive_VBamoPeerImpl_MPCManagerBamo_AutoBamos_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180074180); // 6442926464
