// RVA 0x2093B8, .data
// Symbol: ?s_systemButtonControllerManager@ISMStatics@@0PEAVSystemButtonEventControllerManager@@EA
struct SystemButtonEventControllerManager *_s_systemButtonControllerManager_ISMStatics__0PEAVSystemButtonEventControllerManager__EA = reinterpret_cast<decltype(_s_systemButtonControllerManager_ISMStatics__0PEAVSystemButtonEventControllerManager__EA)>(0x0000000000000000); // 0
