// RVA 0x2094B0, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUwlxpUoryUlyquivUznwGEUkivxlnkOlyq@DockProcessor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUwlxpUoryUlyquivUznwGEUkivxlnkOlyq_DockProcessor = 0x00; // 0
