// RVA 0x2093B4, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUfgrorgrvhUrmkfgxlmurtfizgrlmUlyquivUznwGEUkxsOlyq@InputConfiguration
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUfgrorgrvhUrmkfgxlmurtfizgrlmUlyquivUznwGEUkxsOlyq_InputConfiguration = 0x00; // 0
