// RVA 0x209478, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUfgrorgrvhUzmrnzgrlmwzgzkilerwviUlyquivUznwGEUkxsOlyq@AnimationDataProvider
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUfgrorgrvhUzmrnzgrlmwzgzkilerwviUlyquivUznwGEUkxsOlyq_AnimationDataProvider = 0x00; // 0
