// RVA 0xA53C8, .rdata
// Symbol: ??_7?$AutoBuffer@U_DMM_MONITORPRESENCEEVENTSET_SERIALIZATION@@@DMM@@6BSetElement@@@
void *___7__AutoBuffer_U_DMM_MONITORPRESENCEEVENTSET_SERIALIZATION___DMM__6BSetElement___ = reinterpret_cast<decltype(___7__AutoBuffer_U_DMM_MONITORPRESENCEEVENTSET_SERIALIZATION___DMM__6BSetElement___)>(0x000000014008E8F0); // 5369293040
