// RVA 0xA6BD8, .rdata
// Symbol: ??_7DMMVIDEOPRESENTTARGET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTTARGET@@@@@
void *___7DMMVIDEOPRESENTTARGET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTTARGET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGET_____)>(0x000000014008F680); // 5369296512
