// RVA 0x1636C0, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUxlnklhrgrlmhfiuzxvUlyquivUznwGEUkivxlnkOlyq@CompositionSurface
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUxlnklhrgrlmhfiuzxvUlyquivUznwGEUkivxlnkOlyq_CompositionSurface = 0x00; // 0
