// RVA 0x1634A8, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUnlmrgliUpvimvoUlyquivUznwGEUkivxlnkOlyq@monitor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUnlmrgliUpvimvoUlyquivUznwGEUkivxlnkOlyq_monitor = 0x00; // 0
