// RVA 0x7C7C8, .rdata
// Symbol: ?FlagsDefault@DXGSYNCOBJECT@@1U_D3DDDI_SYNCHRONIZATIONOBJECT_FLAGS@@B
// Type: const struct _D3DDDI_SYNCHRONIZATIONOBJECT_FLAGS
unsigned char _FlagsDefault_DXGSYNCOBJECT__1U_D3DDDI_SYNCHRONIZATIONOBJECT_FLAGS__B[0x4] = {};
