// RVA 0xB57DC, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwlwkivhvmgUlyquivUznwGEUkivxlnkOlyq@dodpresent
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwlwkivhvmgUlyquivUznwGEUkivxlnkOlyq_dodpresent = 0x00; // 0
