// RVA 0x3A3C0, .rdata
// Symbol: ??_7DMMVIDEOPRESENTTARGET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTTARGET@@@@@
void *___7DMMVIDEOPRESENTTARGET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTTARGET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGET_____)>(0x00000001C0016D60); // 7516286304
