// RVA 0x442A8, .rdata
// Symbol: ?VmBusCommandTableHostToVm@DXG_GUEST_VIRTUALGPU_VMBUS@@2QBUDXG_VMBUS_COMMAND_TABLE@@B
unsigned char _VmBusCommandTableHostToVm_DXG_GUEST_VIRTUALGPU_VMBUS__2QBUDXG_VMBUS_COMMAND_TABLE__B = 0x00; // 0
