// RVA 0x237A18, .rdata
// Symbol: ??_7?$CSharedResourceMarshaler@VCVisualReferenceControllerMarshaler@DirectComposition@@$01@DirectComposition@@6B@
void *___7__CSharedResourceMarshaler_VCVisualReferenceControllerMarshaler_DirectComposition___01_DirectComposition__6B_ = reinterpret_cast<decltype(___7__CSharedResourceMarshaler_VCVisualReferenceControllerMarshaler_DirectComposition___01_DirectComposition__6B_)>(0x00000001C00C0260); // 7516979808
