// RVA 0x22F788, .rdata
// Symbol: ??_7?$CSharedResourceMarshaler@VCCompositionDistantLightMarshaler@DirectComposition@@$01@DirectComposition@@6B@
void *___7__CSharedResourceMarshaler_VCCompositionDistantLightMarshaler_DirectComposition___01_DirectComposition__6B_ = reinterpret_cast<decltype(___7__CSharedResourceMarshaler_VCCompositionDistantLightMarshaler_DirectComposition___01_DirectComposition__6B_)>(0x00000001C00B5BB0); // 7516937136
