// RVA 0x28BCA7, .data
// Symbol: ?gpfnHidP_GetUsagesEx@@3V?$SGDRIMgpfnHidP_GetUsagesEx@P6AJW4_HIDP_REPORT_TYPE@@GPEAU_USAGE_AND_PAGE@@PEAKPEAU_HIDP_PREPARSED_DATA@@PEADK@Z@@A
unsigned char _gpfnHidP_GetUsagesEx__3V__SGDRIMgpfnHidP_GetUsagesEx_P6AJW4_HIDP_REPORT_TYPE__GPEAU_USAGE_AND_PAGE__PEAKPEAU_HIDP_PREPARSED_DATA__PEADK_Z__A = 0x00; // 0
