// RVA 0x28BC9F, .data
// Symbol: ?gpfnHidP_SetUsages@@3V?$SGDRIMgpfnHidP_SetUsages@P6AJW4_HIDP_REPORT_TYPE@@GGPEAGPEAKPEAU_HIDP_PREPARSED_DATA@@PEADK@Z@@A
unsigned char _gpfnHidP_SetUsages__3V__SGDRIMgpfnHidP_SetUsages_P6AJW4_HIDP_REPORT_TYPE__GGPEAGPEAKPEAU_HIDP_PREPARSED_DATA__PEADK_Z__A = 0x00; // 0
