// RVA 0x28BC9A, .data
// Symbol: ?gpfnHidP_GetValueCaps@@3V?$SGDRIMgpfnHidP_GetValueCaps@P6AJW4_HIDP_REPORT_TYPE@@PEAU_HIDP_VALUE_CAPS@@PEAGPEAU_HIDP_PREPARSED_DATA@@@Z@@A
unsigned char _gpfnHidP_GetValueCaps__3V__SGDRIMgpfnHidP_GetValueCaps_P6AJW4_HIDP_REPORT_TYPE__PEAU_HIDP_VALUE_CAPS__PEAGPEAU_HIDP_PREPARSED_DATA___Z__A = 0x00; // 0
