// RVA 0x28BCA0, .data
// Symbol: ?gpfnHidP_UnsetUsages@@3V?$SGDRIMgpfnHidP_UnsetUsages@P6AJW4_HIDP_REPORT_TYPE@@GGPEAGPEAKPEAU_HIDP_PREPARSED_DATA@@PEADK@Z@@A
unsigned char _gpfnHidP_UnsetUsages__3V__SGDRIMgpfnHidP_UnsetUsages_P6AJW4_HIDP_REPORT_TYPE__GGPEAGPEAKPEAU_HIDP_PREPARSED_DATA__PEADK_Z__A = 0x00; // 0
