// RVA 0x25A5BC, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUmgtwrUszmwovnzmztviUxlivUpnoryUlyquivUznwGEUkivxlnkOlyq@gdihandlemanagerk
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUmgtwrUszmwovnzmztviUxlivUpnoryUlyquivUznwGEUkivxlnkOlyq_gdihandlemanagerk = 0x00; // 0
