// RVA 0x1F4840, .rdata
// Symbol: ??_7?$ListPrincipal@VBamoSimpleHapticsControllerPrincipal@@@ISMBamos_AutoBamos@Lib@Bamo@Microsoft@@6BIList_SimpleHapticsControllerPrincipal_Principal@1234@@
void *___7__ListPrincipal_VBamoSimpleHapticsControllerPrincipal___ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BIList_SimpleHapticsControllerPrincipal_Principal_1234__ = reinterpret_cast<decltype(___7__ListPrincipal_VBamoSimpleHapticsControllerPrincipal___ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BIList_SimpleHapticsControllerPrincipal_Principal_1234__)>(0x0000000180191930); // 6444095792
