// RVA 0x220D21, .rdata
// Symbol: ?_tlgEvent@?6??LogOnActivationConfigurationInputObjectChanging@BamoInputSiteElementProxy@@AEAAXPEAVBamoActivationConfigurationInputObjectProxy@@@Z@4U_unnamed_type__tlgEvent_@?6??12@AEAAX0@Z@B
unsigned char __tlgEvent__6__LogOnActivationConfigurationInputObjectChanging_BamoInputSiteElementProxy__AEAAXPEAVBamoActivationConfigurationInputObjectProxy___Z_4U_unnamed_type__tlgEvent___6__12_AEAAX0_Z_B = 0x06; // 6
