// RVA 0x223509, .rdata
// Symbol: ?_tlgEvent@?6??LogReceiveUnregisterObserverClientOfType@BamoInputObserverManagerPrincipalImpl@BamoImpl@@AEAAXW4InputObserverType@InputObservation@@PEAVBamoInputObserverClientProxy@@@Z@4U_unnamed_type__tlgEvent_@?6??123@AEAAX01@Z@B
unsigned char __tlgEvent__6__LogReceiveUnregisterObserverClientOfType_BamoInputObserverManagerPrincipalImpl_BamoImpl__AEAAXW4InputObserverType_InputObservation__PEAVBamoInputObserverClientProxy___Z_4U_unnamed_type__tlgEvent___6__123_AEAAX01_Z_B = 0x06; // 6
