// RVA 0x1EB640, .rdata
// Symbol: ?Methods@?$ISimpleHapticsControllerProxy_Receive@VBamoSimpleHapticsControllerProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___ISimpleHapticsControllerProxy_Receive_VBamoSimpleHapticsControllerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___ISimpleHapticsControllerProxy_Receive_VBamoSimpleHapticsControllerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180129E90); // 6443671184
