// RVA 0x1EE830, .rdata
// Symbol: ?Methods@?$IInputObserverManagerPrincipal_Receive@VBamoInputObserverManagerPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IInputObserverManagerPrincipal_Receive_VBamoInputObserverManagerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IInputObserverManagerPrincipal_Receive_VBamoInputObserverManagerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x000000018013C880); // 6443747456
