// RVA 0x1EE5F0, .rdata
// Symbol: ?Methods@?$IWindowsMessageDeliveryProxy_Receive@VBamoWindowsMessageDeliveryProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IWindowsMessageDeliveryProxy_Receive_VBamoWindowsMessageDeliveryProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IWindowsMessageDeliveryProxy_Receive_VBamoWindowsMessageDeliveryProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180079360); // 6442947424
