// RVA 0x1ED900, .rdata
// Symbol: ?Methods@?$IControllerNavigationManagerProxy_Receive@VBamoControllerNavigationManagerProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IControllerNavigationManagerProxy_Receive_VBamoControllerNavigationManagerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IControllerNavigationManagerProxy_Receive_VBamoControllerNavigationManagerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180129F20); // 6443671328
