// RVA 0x1EF600, .rdata
// Symbol: ?Methods@?$IAnimationTargetClientProxy_Receive@VBamoAnimationTargetClientProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IAnimationTargetClientProxy_Receive_VBamoAnimationTargetClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IAnimationTargetClientProxy_Receive_VBamoAnimationTargetClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180091460); // 6443045984
