// RVA 0x1F8E58, .rdata
// Symbol: ?Type@?$IList_VirtualTouchpadRect_Proxy_Receive@VBamoList_VirtualTouchpadRect_ProxyImpl@ISMBamos_AutoBamos@BamoImpl@Lib@Bamo@Microsoft@@@ISMBamos_AutoBamos@Lib@Bamo@Microsoft@@2UMsgCallTypeDefinition@@B
unsigned char _Type___IList_VirtualTouchpadRect_Proxy_Receive_VBamoList_VirtualTouchpadRect_ProxyImpl_ISMBamos_AutoBamos_BamoImpl_Lib_Bamo_Microsoft___ISMBamos_AutoBamos_Lib_Bamo_Microsoft__2UMsgCallTypeDefinition__B = 0x01; // 1
