// RVA 0x257B18, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUwiztmwilkUhbhgvnUoryUlyquivUznwGEUkxsOlyq@DragNDropProcessor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUwiztmwilkUhbhgvnUoryUlyquivUznwGEUkxsOlyq_DragNDropProcessor = 0x00; // 0
