// RVA 0x257B00, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUhbhgvnxlmgvcgUnzmztviUlyquivUznwGEUkxsOlyq@SystemContextManager
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUhbhgvnxlmgvcgUnzmztviUlyquivUznwGEUkxsOlyq_SystemContextManager = 0x00; // 0
