// RVA 0x2576C8, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUulivtilfmwnzmztviUhvieviUlyquivUznwGEUkxsOlyq@ForegroundManagerServer
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUulivtilfmwnzmztviUhvieviUlyquivUznwGEUkxsOlyq_ForegroundManagerServer = 0x00; // 0
