// RVA 0x257C1C, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUsvzgUoryUlyquivUznwGEUkxsOlyq@HeatProcessor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUsvzgUoryUlyquivUznwGEUkxsOlyq_HeatProcessor = 0x00; // 0
