// RVA 0x1E8A28, .rdata
// Symbol: ??_7?$RuntimeClass@U?$RuntimeClassFlags@$01@WRL@Microsoft@@UIContextualProcessor@@UITextInputStateAdapterOwner@@UIInputServiceProxyOwner@@@WRL@Microsoft@@6B@
void *___7__RuntimeClass_U__RuntimeClassFlags__01_WRL_Microsoft__UIContextualProcessor__UITextInputStateAdapterOwner__UIInputServiceProxyOwner___WRL_Microsoft__6B_ = reinterpret_cast<decltype(___7__RuntimeClass_U__RuntimeClassFlags__01_WRL_Microsoft__UIContextualProcessor__UITextInputStateAdapterOwner__UIInputServiceProxyOwner___WRL_Microsoft__6B_)>(0x0000000180197DE0); // 6444121568
