// RVA 0x1E0310, .rdata
// Symbol: ??_7BamoEdgyGestureRecognitionConfigurationProxy@@6BIEdgyGestureRecognitionConfigurationProxy@@@
void *___7BamoEdgyGestureRecognitionConfigurationProxy__6BIEdgyGestureRecognitionConfigurationProxy___ = reinterpret_cast<decltype(___7BamoEdgyGestureRecognitionConfigurationProxy__6BIEdgyGestureRecognitionConfigurationProxy___)>(0x000000018011FE50); // 6443630160
