// RVA 0x20CDC5, .rdata
// Symbol: ?_tlgEvent@?6??LogOnGestureRecognitionConfigurationChanging@BamoEdgyDragSourceClientProxy@@AEAAXPEAVBamoEdgyGestureRecognitionConfigurationProxy@@@Z@4U_unnamed_type__tlgEvent_@?6??12@AEAAX0@Z@B
unsigned char __tlgEvent__6__LogOnGestureRecognitionConfigurationChanging_BamoEdgyDragSourceClientProxy__AEAAXPEAVBamoEdgyGestureRecognitionConfigurationProxy___Z_4U_unnamed_type__tlgEvent___6__12_AEAAX0_Z_B = 0x06; // 6
