// RVA 0x21B53B, .rdata
// Symbol: ?_tlgEvent@?6??LogSetSupportedFeedback@BamoSimpleHapticsControllerPrincipalImpl@BamoImpl@@AEAAXPEAVBamoList_SimpleHapticsControllerFeedback_Principal@ISMBamos_AutoBamos@Lib@Bamo@Microsoft@@@Z@4U_unnamed_type__tlgEvent_@?6??123@AEAAX0@Z@B
unsigned char __tlgEvent__6__LogSetSupportedFeedback_BamoSimpleHapticsControllerPrincipalImpl_BamoImpl__AEAAXPEAVBamoList_SimpleHapticsControllerFeedback_Principal_ISMBamos_AutoBamos_Lib_Bamo_Microsoft___Z_4U_unnamed_type__tlgEvent___6__123_AEAAX0_Z_B = 0x06; // 6
