// RVA 0x1E6838, .rdata
// Symbol: ?Methods@?$IMPCConstantManagerClientCallbacksPrincipal_Receive@VBamoMPCConstantManagerClientCallbacksPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IMPCConstantManagerClientCallbacksPrincipal_Receive_VBamoMPCConstantManagerClientCallbacksPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IMPCConstantManagerClientCallbacksPrincipal_Receive_VBamoMPCConstantManagerClientCallbacksPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180174090); // 6443974800
