// RVA 0x1E00D0, .rdata
// Symbol: ?Methods@?$ICursorSuppressionPolicyObjectProxy_Receive@VBamoCursorSuppressionPolicyObjectProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___ICursorSuppressionPolicyObjectProxy_Receive_VBamoCursorSuppressionPolicyObjectProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___ICursorSuppressionPolicyObjectProxy_Receive_VBamoCursorSuppressionPolicyObjectProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180124E40); // 6443650624
