// RVA 0x1E7160, .rdata
// Symbol: ?Methods@?$IHeatGripServicePrincipal_Receive@VBamoHeatGripServicePrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IHeatGripServicePrincipal_Receive_VBamoHeatGripServicePrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IHeatGripServicePrincipal_Receive_VBamoHeatGripServicePrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180183020); // 6444036128
