// RVA 0x1DB4C0, .rdata
// Symbol: ?Methods@?$IMPCConstantManagerClientPrincipal_Receive@VBamoMPCConstantManagerClientPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IMPCConstantManagerClientPrincipal_Receive_VBamoMPCConstantManagerClientPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IMPCConstantManagerClientPrincipal_Receive_VBamoMPCConstantManagerClientPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x00000001800B7580); // 6443201920
