// RVA 0x1E8768, .rdata
// Symbol: ?Methods@?$IInputInjectionClientProxy_Receive@VBamoInputInjectionClientProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IInputInjectionClientProxy_Receive_VBamoInputInjectionClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IInputInjectionClientProxy_Receive_VBamoInputInjectionClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x00000001801961E0); // 6444114400
