// RVA 0x2479C8, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUwiztmwilkUhbhgvnUoryUlyquivUznwGEUkxsOlyq@DragNDropProcessor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUwiztmwilkUhbhgvnUoryUlyquivUznwGEUkxsOlyq_DragNDropProcessor = 0x00; // 0
