// RVA 0x247668, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUnkxUoryUlyquivUznwGEUkivxlnkOlyq@MPCProcessor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUnkxUoryUlyquivUznwGEUkivxlnkOlyq_MPCProcessor = 0x00; // 0
