// RVA 0x2479B4, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUxlnklmvmghUrmkfgtvhgfivhUhbhgvnUlyquivUznwGEUkxsOlyq@GestureServices
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUxlnklmvmghUrmkfgtvhgfivhUhbhgvnUlyquivUznwGEUkxsOlyq_GestureServices = 0x00; // 0
