// RVA 0x247A90, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUwlxpUhvieviUlyquivUznwGEUkivxlnkOlyq@DeviceDockServer
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUwlxpUhvieviUlyquivUznwGEUkivxlnkOlyq_DeviceDockServer = 0x00; // 0
