// RVA 0x24778C, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUizdrmkfgkilerwvihUoznkziizbUoryUlyquivUznwGEUkivxlnkOlyq@LampArrayRawInputProvider
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUizdrmkfgkilerwvihUoznkziizbUoryUlyquivUznwGEUkivxlnkOlyq_LampArrayRawInputProvider = 0x00; // 0
