// RVA 0x247888, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUhbhgvnrmkfgilfgvihUnkxUoryUlyquivUznwGEUkivxlnkOlyq@MPCInputRouter
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUhbhgvnrmkfgilfgvihUnkxUoryUlyquivUznwGEUkivxlnkOlyq_MPCInputRouter = 0x00; // 0
