// RVA 0x17B5E8, .rdata
// Symbol: ??_7SimpleTimeProvider@HapticsEngine@SpatialInteractions@Internal@Windows@@6BITimerElapsedHandler@Threading@System@4@@
void *___7SimpleTimeProvider_HapticsEngine_SpatialInteractions_Internal_Windows__6BITimerElapsedHandler_Threading_System_4__ = reinterpret_cast<decltype(___7SimpleTimeProvider_HapticsEngine_SpatialInteractions_Internal_Windows__6BITimerElapsedHandler_Threading_System_4__)>(0x000000018003A880); // 6442690688
