// RVA 0x16C8D0, .rdata
// Symbol: ??_7SpatialInteractionSourceDeviceCollection@SpatialInteractions@Internal@Windows@@6BISpatialObjectDeviceWatcherCallback@Holographic@23@@
void *___7SpatialInteractionSourceDeviceCollection_SpatialInteractions_Internal_Windows__6BISpatialObjectDeviceWatcherCallback_Holographic_23__ = reinterpret_cast<decltype(___7SpatialInteractionSourceDeviceCollection_SpatialInteractions_Internal_Windows__6BISpatialObjectDeviceWatcherCallback_Holographic_23__)>(0x0000000180039320); // 6442685216
