// RVA 0x17A738, .rdata
// Symbol: ??_7HotKeyProcessor@@6B?$ImplementsHelper@U?$RuntimeClassFlags@$01@WRL@Microsoft@@$00UIMessageProxyReconnectAdapterOwner@@@Details@WRL@Microsoft@@@
void *___7HotKeyProcessor__6B__ImplementsHelper_U__RuntimeClassFlags__01_WRL_Microsoft___00UIMessageProxyReconnectAdapterOwner___Details_WRL_Microsoft___ = reinterpret_cast<decltype(___7HotKeyProcessor__6B__ImplementsHelper_U__RuntimeClassFlags__01_WRL_Microsoft___00UIMessageProxyReconnectAdapterOwner___Details_WRL_Microsoft___)>(0x000000018003A590); // 6442689936
