// RVA 0x172730, .rdata
// Symbol: ?Methods@?$IEdgyControllerServerPrincipal_Receive@VBamoEdgyControllerServerPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IEdgyControllerServerPrincipal_Receive_VBamoEdgyControllerServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IEdgyControllerServerPrincipal_Receive_VBamoEdgyControllerServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x000000018006F8A0); // 6442907808
