// RVA 0x172950, .rdata
// Symbol: ?Methods@?$IBamoPeer_MPCManagerBamo_AutoBamos_Receive@VBamoPeerImpl@MPCManagerBamo_AutoBamos@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
_UNKNOWN *_Methods___IBamoPeer_MPCManagerBamo_AutoBamos_Receive_VBamoPeerImpl_MPCManagerBamo_AutoBamos_BamoImpl____2QBUMsgCallMethodDefinition__B = reinterpret_cast<decltype(_Methods___IBamoPeer_MPCManagerBamo_AutoBamos_Receive_VBamoPeerImpl_MPCManagerBamo_AutoBamos_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x000000018007F870); // 6442973296
