// RVA 0x172220, .rdata
// Symbol: ?Methods@?$IControllerNavigationManagerProxy_Receive@VBamoControllerNavigationManagerProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IControllerNavigationManagerProxy_Receive_VBamoControllerNavigationManagerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IControllerNavigationManagerProxy_Receive_VBamoControllerNavigationManagerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180063260); // 6442857056
