// RVA 0x1E17DC, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUfgrorgrvhUrhnhgzgrxhUlyquivUznwGEUkxsOlyq@ISMStatics
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUfgrorgrvhUrhnhgzgrxhUlyquivUznwGEUkxsOlyq_ISMStatics = 0x00; // 0
