// RVA 0x1A64B4, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUmgfhviUpvimvoUrmkfgUkgkUpnUlyquivUznwGEUkivxlnkOlyq@ptpEngine
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUmgfhviUpvimvoUrmkfgUkgkUpnUlyquivUznwGEUkivxlnkOlyq_ptpEngine = 0x00; // 0
