// RVA 0x1D9720, .rdata
// Symbol: ??_7BamoList_ActivatableEntityPrincipal_Stub@ISMBamos_AutoBamos@Lib@Bamo@Microsoft@@6BIList_ActivatableEntityPrincipal_Stub@1234@@
void *___7BamoList_ActivatableEntityPrincipal_Stub_ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BIList_ActivatableEntityPrincipal_Stub_1234__ = reinterpret_cast<decltype(___7BamoList_ActivatableEntityPrincipal_Stub_ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BIList_ActivatableEntityPrincipal_Stub_1234__)>(0x000000018004ECC0); // 6442773696
