// RVA 0x1EDB30, .rdata
// Symbol: ??_7?$RuntimeClass@U?$RuntimeClassFlags@$01@WRL@Microsoft@@UIContextualProcessor@@UITextInputStateAdapterOwner@@UIInputServiceProxyOwner@@@WRL@Microsoft@@6B@
void *___7__RuntimeClass_U__RuntimeClassFlags__01_WRL_Microsoft__UIContextualProcessor__UITextInputStateAdapterOwner__UIInputServiceProxyOwner___WRL_Microsoft__6B_ = reinterpret_cast<decltype(___7__RuntimeClass_U__RuntimeClassFlags__01_WRL_Microsoft__UIContextualProcessor__UITextInputStateAdapterOwner__UIInputServiceProxyOwner___WRL_Microsoft__6B_)>(0x000000018019B270); // 6444135024
