// RVA 0x1ED380, .rdata
// Symbol: ??_7BamoList_SimpleHapticsControllerFeedback_Principal@ISMBamos_AutoBamos@Lib@Bamo@Microsoft@@6BIList_SimpleHapticsControllerFeedback_Principal@1234@@
void *___7BamoList_SimpleHapticsControllerFeedback_Principal_ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BIList_SimpleHapticsControllerFeedback_Principal_1234__ = reinterpret_cast<decltype(___7BamoList_SimpleHapticsControllerFeedback_Principal_ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BIList_SimpleHapticsControllerFeedback_Principal_1234__)>(0x0000000180052B40); // 6442789696
