// RVA 0x1E3990, .rdata
// Symbol: ?Methods@?$IInputDeliveryServerPrincipal_Receive@VBamoInputDeliveryServerPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IInputDeliveryServerPrincipal_Receive_VBamoInputDeliveryServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IInputDeliveryServerPrincipal_Receive_VBamoInputDeliveryServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180153FD0); // 6443843536
