// RVA 0x1E2E60, .rdata
// Symbol: ?Methods@?$ISystemContextEndpointPrincipal_Receive@VBamoSystemContextEndpointPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___ISystemContextEndpointPrincipal_Receive_VBamoSystemContextEndpointPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___ISystemContextEndpointPrincipal_Receive_VBamoSystemContextEndpointPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180088880); // 6443010176
