// RVA 0x1E4160, .rdata
// Symbol: ?Methods@?$IBamoPeer_dataprovider_AutoBamos_Receive@VBamoPeerImpl@dataprovider_AutoBamos@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
_UNKNOWN *_Methods___IBamoPeer_dataprovider_AutoBamos_Receive_VBamoPeerImpl_dataprovider_AutoBamos_BamoImpl____2QBUMsgCallMethodDefinition__B = reinterpret_cast<decltype(_Methods___IBamoPeer_dataprovider_AutoBamos_Receive_VBamoPeerImpl_dataprovider_AutoBamos_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180048AF0); // 6442748656
