// RVA 0x1E3860, .rdata
// Symbol: ?Methods@?$IResizeContextualProcessorPrincipal_Receive@VBamoResizeContextualProcessorPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IResizeContextualProcessorPrincipal_Receive_VBamoResizeContextualProcessorPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IResizeContextualProcessorPrincipal_Receive_VBamoResizeContextualProcessorPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180143C00); // 6443777024
