// RVA 0x1E30A0, .rdata
// Symbol: ?Methods@?$ISystemCursorControllerPrincipal_Receive@VBamoSystemCursorControllerPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___ISystemCursorControllerPrincipal_Receive_VBamoSystemCursorControllerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___ISystemCursorControllerPrincipal_Receive_VBamoSystemCursorControllerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x00000001800EA390); // 6443410320
