// RVA 0x1E34F0, .rdata
// Symbol: ?Methods@?$IInputForwardTargetInputObjectProxy_Receive@VBamoInputForwardTargetInputObjectProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IInputForwardTargetInputObjectProxy_Receive_VBamoInputForwardTargetInputObjectProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IInputForwardTargetInputObjectProxy_Receive_VBamoInputForwardTargetInputObjectProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180118E90); // 6443601552
