// RVA 0x2434D8, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUizdrmkfgkilerwvihUirnUoryUlyquivUznwGEUkivxlnkOlyq@RIMRawInputProvider
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUizdrmkfgkilerwvihUirnUoryUlyquivUznwGEUkivxlnkOlyq_RIMRawInputProvider = 0x00; // 0
