// RVA 0x243640, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUsvzgUoryUlyquivUznwGEUkxsOlyq@HeatProcessor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUsvzgUoryUlyquivUznwGEUkxsOlyq_HeatProcessor = 0x00; // 0
