// RVA 0x2435D4, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUyznlhUhvieviUhbhgvnUlyquivUznwGEUkxsOlyq@ISMBamoServer
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUyznlhUhvieviUhbhgvnUlyquivUznwGEUkxsOlyq_ISMBamoServer = 0x00; // 0
