// RVA 0xE0EA60, .data
// Symbol: ?ThresholdShiftTableInMem@?1??StDmCheckForCompaction@?$ST_STORE@USM_TRAITS@@@@SA?AW4_ST_COMPACTION_CHECK_RESULT@@PEAU_ST_DATA_MGR@2@KPEAK@Z@4PAY01EA
char _ThresholdShiftTableInMem__1__StDmCheckForCompaction___ST_STORE_USM_TRAITS____SA_AW4_ST_COMPACTION_CHECK_RESULT__PEAU_ST_DATA_MGR_2_KPEAK_Z_4PAY01EA = 0x04; // 4
