// RVA 0x1AA298, .rdata
// Symbol: ??_7BamoDragNDropContextualProcessorPrincipal@@6BIDragNDropContextualProcessorPrincipal@@@
void *___7BamoDragNDropContextualProcessorPrincipal__6BIDragNDropContextualProcessorPrincipal___ = reinterpret_cast<decltype(___7BamoDragNDropContextualProcessorPrincipal__6BIDragNDropContextualProcessorPrincipal___)>(0x000000018004BA80); // 6442760832
