// RVA 0x1B1A00, .rdata
// Symbol: ??_7FinalizeControllerInitialization@SpatialInteractionTrace@SpatialInteractionDevices@@6B@
void *___7FinalizeControllerInitialization_SpatialInteractionTrace_SpatialInteractionDevices__6B_ = reinterpret_cast<decltype(___7FinalizeControllerInitialization_SpatialInteractionTrace_SpatialInteractionDevices__6B_)>(0x00000001800D07E0); // 6443304928
