// RVA 0x1B75F0, .rdata
// Symbol: ??_7?$RuntimeClass@U?$RuntimeClassFlags@$01@WRL@Microsoft@@UIInputTarget@@UIInputDestComparable@@UIInputDestInputTarget@@@WRL@Microsoft@@6BIInputDestComparable@@@
void *___7__RuntimeClass_U__RuntimeClassFlags__01_WRL_Microsoft__UIInputTarget__UIInputDestComparable__UIInputDestInputTarget___WRL_Microsoft__6BIInputDestComparable___ = reinterpret_cast<decltype(___7__RuntimeClass_U__RuntimeClassFlags__01_WRL_Microsoft__UIInputTarget__UIInputDestComparable__UIInputDestInputTarget___WRL_Microsoft__6BIInputDestComparable___)>(0x000000018004CC80); // 6442765440
