// RVA 0x1A93D8, .rdata
// Symbol: ??_7SpatialInteractionSourceDeviceCollection@SpatialInteractions@Internal@Windows@@6BISpatialObjectDeviceWatcherCallback@Holographic@23@@
void *___7SpatialInteractionSourceDeviceCollection_SpatialInteractions_Internal_Windows__6BISpatialObjectDeviceWatcherCallback_Holographic_23__ = reinterpret_cast<decltype(___7SpatialInteractionSourceDeviceCollection_SpatialInteractions_Internal_Windows__6BISpatialObjectDeviceWatcherCallback_Holographic_23__)>(0x000000018004B720); // 6442759968
