// RVA 0x1B1EC8, .rdata
// Symbol: ??_7InitializeSpatialObjectDeviceSupport@SpatialInteractionTrace@SpatialInteractionDevices@@6B@
void *___7InitializeSpatialObjectDeviceSupport_SpatialInteractionTrace_SpatialInteractionDevices__6B_ = reinterpret_cast<decltype(___7InitializeSpatialObjectDeviceSupport_SpatialInteractionTrace_SpatialInteractionDevices__6B_)>(0x00000001800D0B30); // 6443305776
