// RVA 0x1AFD80, .rdata
// Symbol: ?Methods@?$IVirtualTouchpadControllerProxy_Receive@VBamoVirtualTouchpadControllerProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IVirtualTouchpadControllerProxy_Receive_VBamoVirtualTouchpadControllerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IVirtualTouchpadControllerProxy_Receive_VBamoVirtualTouchpadControllerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x00000001800F0FE0); // 6443438048
