// RVA 0x1AFF40, .rdata
// Symbol: ?Methods@?$ISystemButtonEventControllerProxy_Receive@VBamoSystemButtonEventControllerProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___ISystemButtonEventControllerProxy_Receive_VBamoSystemButtonEventControllerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___ISystemButtonEventControllerProxy_Receive_VBamoSystemButtonEventControllerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180102910); // 6443510032
