// RVA 0x20A4A4, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUhgbofhUzkrUhvieviUlyquivUznwGEUkivxlnkOlyq@PenDeviceServer
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUhgbofhUzkrUhvieviUlyquivUznwGEUkivxlnkOlyq_PenDeviceServer = 0x00; // 0
