// RVA 0x20A42C, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUyznlhUhvieviUlyquivUznwGEUkxsOlyq@ISMBamoServer
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUyznlhUhvieviUlyquivUznwGEUkxsOlyq_ISMBamoServer = 0x00; // 0
