// RVA 0x20A3B8, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUizdrmkfgkilerwvihUoznkziizbUoryUlyquivUznwGEUkivxlnkOlyq@LampArrayRawInputProvider
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUizdrmkfgkilerwvihUoznkziizbUoryUlyquivUznwGEUkivxlnkOlyq_LampArrayRawInputProvider = 0x00; // 0
