// RVA 0x20A440, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUivhravUhbhgvnUoryUlyquivUznwGEUkxsOlyq@ResizeProcessor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUivhravUhbhgvnUoryUlyquivUznwGEUkxsOlyq_ResizeProcessor = 0x00; // 0
