// RVA 0xCF8C0, .rdata
int *Feature_Servicing_DefaultProfileIntervalQueryErrorETLVMPlatforms__private_descriptor = reinterpret_cast<decltype(Feature_Servicing_DefaultProfileIntervalQueryErrorETLVMPlatforms__private_descriptor)>(0x0000000140CF7DE8); // 5382307304
