// RVA 0x1A9718, .rdata
// Symbol: ??_7MessageProxyReconnectAdapter@@6B?$ImplementsHelper@U?$RuntimeClassFlags@$01@WRL@Microsoft@@$00UIMessageProxyListener@@@Details@WRL@Microsoft@@@
void *___7MessageProxyReconnectAdapter__6B__ImplementsHelper_U__RuntimeClassFlags__01_WRL_Microsoft___00UIMessageProxyListener___Details_WRL_Microsoft___ = reinterpret_cast<decltype(___7MessageProxyReconnectAdapter__6B__ImplementsHelper_U__RuntimeClassFlags__01_WRL_Microsoft___00UIMessageProxyListener___Details_WRL_Microsoft___)>(0x000000018004BB80); // 6442761088
