// RVA 0x1B1EE8, .rdata
// Symbol: ??_7InitializeSpatialObjectDeviceSupport@SpatialInteractionTrace@SpatialInteractionDevices@@6B@
void *___7InitializeSpatialObjectDeviceSupport_SpatialInteractionTrace_SpatialInteractionDevices__6B_ = reinterpret_cast<decltype(___7InitializeSpatialObjectDeviceSupport_SpatialInteractionTrace_SpatialInteractionDevices__6B_)>(0x00000001800D0A40); // 6443305536
