// RVA 0x1CF8F5, .rdata
// Symbol: ?_tlgEvent@?5??StartActivity@CreateSpatialGraphNodeReference@HolographicDriverClientContinuousTrace@@QEAAXAEBU_GUID@@AEBUSPATIAL_NODE_ID@@W4SPATIAL_TRACKING_STATE@@@Z@4U_unnamed_type__tlgEvent_@?5??123@QEAAX012@Z@B
unsigned char __tlgEvent__5__StartActivity_CreateSpatialGraphNodeReference_HolographicDriverClientContinuousTrace__QEAAXAEBU_GUID__AEBUSPATIAL_NODE_ID__W4SPATIAL_TRACKING_STATE___Z_4U_unnamed_type__tlgEvent___5__123_QEAAX012_Z_B = 0x06; // 6
