// RVA 0x20A4C0, .data
// Symbol: ?s_DynamicNodeInfoBindingWaitBeforeRetryMilliseconds@SpatialInteractionSourceController@SpatialInteractions@Internal@Windows@@0KA
DWORD _s_DynamicNodeInfoBindingWaitBeforeRetryMilliseconds_SpatialInteractionSourceController_SpatialInteractions_Internal_Windows__0KA = 0x00000000; // 0
