// RVA 0x3C714, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwctnnhCUerwhxsUlyquivUznwGEUkivxlnkOlyq@vidsch2
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwctnnhCUerwhxsUlyquivUznwGEUkivxlnkOlyq_vidsch2 = 0x00; // 0
