// RVA 0x1F4698, .rdata
// Symbol: ??_7BamoList_SimpleHapticsControllerPrincipal_PrincipalImpl@ISMBamos_AutoBamos@BamoImpl@Lib@Bamo@Microsoft@@6B@
void *___7BamoList_SimpleHapticsControllerPrincipal_PrincipalImpl_ISMBamos_AutoBamos_BamoImpl_Lib_Bamo_Microsoft__6B_ = reinterpret_cast<decltype(___7BamoList_SimpleHapticsControllerPrincipal_PrincipalImpl_ISMBamos_AutoBamos_BamoImpl_Lib_Bamo_Microsoft__6B_)>(0x000000018005D3F0); // 6442832880
