// RVA 0x1F45F0, .rdata
// Symbol: ??_7BamoList_SimpleHapticsControllerPrincipal_Principal@ISMBamos_AutoBamos@Lib@Bamo@Microsoft@@6BBamoPrincipal@34@@
void *___7BamoList_SimpleHapticsControllerPrincipal_Principal_ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BBamoPrincipal_34__ = reinterpret_cast<decltype(___7BamoList_SimpleHapticsControllerPrincipal_Principal_ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BBamoPrincipal_34__)>(0x0000000180074B70); // 6442929008
