// RVA 0x1F4120, .rdata
// Symbol: ??_7BamoList_SimpleHapticsControllerFeedback_Stub@ISMBamos_AutoBamos@Lib@Bamo@Microsoft@@6BIList_SimpleHapticsControllerFeedback_Stub@1234@@
void *___7BamoList_SimpleHapticsControllerFeedback_Stub_ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BIList_SimpleHapticsControllerFeedback_Stub_1234__ = reinterpret_cast<decltype(___7BamoList_SimpleHapticsControllerFeedback_Stub_ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BIList_SimpleHapticsControllerFeedback_Stub_1234__)>(0x000000018018B860); // 6444071008
