// RVA 0x227E3D, .rdata
// Symbol: ?_tlgEvent@?6??LogReceiveRegisterShellHandwritingHostClient@BamoShellHandwritingHostServerPrincipalImpl@BamoImpl@@AEAAXPEAVBamoShellHandwritingHostClientProxy@@@Z@4U_unnamed_type__tlgEvent_@?6??123@AEAAX0@Z@B
unsigned char __tlgEvent__6__LogReceiveRegisterShellHandwritingHostClient_BamoShellHandwritingHostServerPrincipalImpl_BamoImpl__AEAAXPEAVBamoShellHandwritingHostClientProxy___Z_4U_unnamed_type__tlgEvent___6__123_AEAAX0_Z_B = 0x06; // 6
