// RVA 0x21F6DE, .rdata
// Symbol: ?_tlgEvent@?6??LogOnGestureRecognitionConfigurationChanging@BamoEdgyNotificationSourceClientProxy@@AEAAXPEAVBamoEdgyGestureRecognitionConfigurationProxy@@@Z@4U_unnamed_type__tlgEvent_@?6??12@AEAAX0@Z@B
unsigned char __tlgEvent__6__LogOnGestureRecognitionConfigurationChanging_BamoEdgyNotificationSourceClientProxy__AEAAXPEAVBamoEdgyGestureRecognitionConfigurationProxy___Z_4U_unnamed_type__tlgEvent___6__12_AEAAX0_Z_B = 0x06; // 6
