// RVA 0x22B766, .rdata
// Symbol: ?_tlgEvent@?6??LogReceiveRemoteInsert@BamoList_TouchInjectionContact_ProxyImpl@ISMBamos_AutoBamos@BamoImpl@Lib@Bamo@Microsoft@@AEAAXIAEBUTouchInjectionContact@Input@Internal@UI@Windows@@@Z@4U_unnamed_type__tlgEvent_@?6??1234567@AEAAXI0@Z@B
unsigned char __tlgEvent__6__LogReceiveRemoteInsert_BamoList_TouchInjectionContact_ProxyImpl_ISMBamos_AutoBamos_BamoImpl_Lib_Bamo_Microsoft__AEAAXIAEBUTouchInjectionContact_Input_Internal_UI_Windows___Z_4U_unnamed_type__tlgEvent___6__1234567_AEAAXI0_Z_B = 0x06; // 6
