// RVA 0x22827E, .rdata
// Symbol: ?_tlgEvent@?6??LogReceiveRegisterInputAttemptedClient@BamoInputDeliveryServerPrincipalImpl@BamoImpl@@AEAAXPEAVBamoInputAttemptedDeliveryClientProxy@@@Z@4U_unnamed_type__tlgEvent_@?6??123@AEAAX0@Z@B
unsigned char __tlgEvent__6__LogReceiveRegisterInputAttemptedClient_BamoInputDeliveryServerPrincipalImpl_BamoImpl__AEAAXPEAVBamoInputAttemptedDeliveryClientProxy___Z_4U_unnamed_type__tlgEvent___6__123_AEAAX0_Z_B = 0x06; // 6
