// RVA 0x21FFB8, .rdata
// Symbol: ?_tlgEvent@?6??LogReceiveRegisterInputSiteElementWithHint@BamoInputSiteManagerPrincipalImpl@BamoImpl@@AEAAXPEAVBamoInputSiteElementProxy@@AEBUInputSiteId@@@Z@4U_unnamed_type__tlgEvent_@?6??123@AEAAX01@Z@B
unsigned char __tlgEvent__6__LogReceiveRegisterInputSiteElementWithHint_BamoInputSiteManagerPrincipalImpl_BamoImpl__AEAAXPEAVBamoInputSiteElementProxy__AEBUInputSiteId___Z_4U_unnamed_type__tlgEvent___6__123_AEAAX01_Z_B = 0x06; // 6
