// RVA 0x2284C4, .rdata
// Symbol: ?_tlgEvent@?6??LogReceiveRegisterOverride@BamoControllerNavigationManagerPrincipalImpl@BamoImpl@@AEAAXPEAVBamoControllerNavigationOverrideProxy@@@Z@4U_unnamed_type__tlgEvent_@?6??123@AEAAX0@Z@B
unsigned char __tlgEvent__6__LogReceiveRegisterOverride_BamoControllerNavigationManagerPrincipalImpl_BamoImpl__AEAAXPEAVBamoControllerNavigationOverrideProxy___Z_4U_unnamed_type__tlgEvent___6__123_AEAAX0_Z_B = 0x06; // 6
