// RVA 0x21BD05, .rdata
// Symbol: ?_tlgEvent@?6??LogOnSupportedFeedbackChanging@BamoSimpleHapticsControllerProxy@@AEAAXPEAVBamoList_SimpleHapticsControllerFeedback_Proxy@ISMBamos_AutoBamos@Lib@Bamo@Microsoft@@@Z@4U_unnamed_type__tlgEvent_@?6??12@AEAAX0@Z@B
unsigned char __tlgEvent__6__LogOnSupportedFeedbackChanging_BamoSimpleHapticsControllerProxy__AEAAXPEAVBamoList_SimpleHapticsControllerFeedback_Proxy_ISMBamos_AutoBamos_Lib_Bamo_Microsoft___Z_4U_unnamed_type__tlgEvent___6__12_AEAAX0_Z_B = 0x06; // 6
