// RVA 0x1EF460, .rdata
// Symbol: ?Methods@?$IAnimationTargetClientProxy_Receive@VBamoAnimationTargetClientProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IAnimationTargetClientProxy_Receive_VBamoAnimationTargetClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IAnimationTargetClientProxy_Receive_VBamoAnimationTargetClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x000000018008EFB0); // 6443036592
