// RVA 0x1F3A30, .rdata
// Symbol: ?Methods@?$IControllerNavigationClientProxy_Receive@VBamoControllerNavigationClientProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IControllerNavigationClientProxy_Receive_VBamoControllerNavigationClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IControllerNavigationClientProxy_Receive_VBamoControllerNavigationClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x000000018017B4B0); // 6444004528
