// RVA 0x2567E8, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUkmksvokviUoryUlyquivUznwGEUkivxlnkOlyq@Pnphelper
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUkmksvokviUoryUlyquivUznwGEUkivxlnkOlyq_Pnphelper = 0x00; // 0
