// RVA 0x256A84, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUzggzxszyovrmkfglyqvxgUhbhgvnUerigfzoglfxskzwxlmgilooviUhvieviUlyquivUznwGEUkivxlnkOlyq@VirtualTouchpadControllerProxy
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUzggzxszyovrmkfglyqvxgUhbhgvnUerigfzoglfxskzwxlmgilooviUhvieviUlyquivUznwGEUkivxlnkOlyq_VirtualTouchpadControllerProxy = 0x00; // 0
