// RVA 0x256D24, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUhsvooszmwdirgrmtUkilxvhhliUlyquivUznwGEUkxsOlyq@ShellHandwritingProcessor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUhsvooszmwdirgrmtUkilxvhhliUlyquivUznwGEUkxsOlyq_ShellHandwritingProcessor = 0x00; // 0
