// RVA 0x256AF4, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUhsvooszmwdirgrmtUhvieviUlyquivUznwGEUkxsOlyq@ShellHandwritingServer
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUhsvooszmwdirgrmtUhvieviUlyquivUznwGEUkxsOlyq_ShellHandwritingServer = 0x00; // 0
