// RVA 0x256BE0, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUhgbofhUvevmghUhvieviUlyquivUznwGEUkxsOlyq@PenEventsServer
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUhgbofhUvevmghUhvieviUlyquivUznwGEUkxsOlyq_PenEventsServer = 0x00; // 0
