// RVA 0x256B10, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgslhgUxlnklmvmghUxfihliUhbhgvnxfihlihvierxvUoryUlyquivUznwGEUkxsOlyq@CursorVisuals
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgslhgUxlnklmvmghUxfihliUhbhgvnxfihlihvierxvUoryUlyquivUznwGEUkxsOlyq_CursorVisuals = 0x00; // 0
