// RVA 0x1CEFA8, .data
// Symbol: ?gpfnHidP_GetUsagesEx@@3P6AJW4_HIDP_REPORT_TYPE@@GPEAU_USAGE_AND_PAGE@@PEAKPEAU_HIDP_PREPARSED_DATA@@PEADK@ZEA
int (*_gpfnHidP_GetUsagesEx__3P6AJW4_HIDP_REPORT_TYPE__GPEAU_USAGE_AND_PAGE__PEAKPEAU_HIDP_PREPARSED_DATA__PEADK_ZEA)(enum _HIDP_REPORT_TYPE, unsigned __int16, struct _USAGE_AND_PAGE *, unsigned int *, struct _HIDP_PREPARSED_DATA *, char *, unsigned int) = reinterpret_cast<decltype(_gpfnHidP_GetUsagesEx__3P6AJW4_HIDP_REPORT_TYPE__GPEAU_USAGE_AND_PAGE__PEAKPEAU_HIDP_PREPARSED_DATA__PEADK_ZEA)>(0x0000000000000000); // 0
