// RVA 0xAB4D8, .rdata
// Symbol: ??_7COMMITVIDPNREQUEST@VIDPN_MGR@@6B?$SignedWithClassSignature@UCOMMITVIDPNREQUEST@VIDPN_MGR@@@@@
void *___7COMMITVIDPNREQUEST_VIDPN_MGR__6B__SignedWithClassSignature_UCOMMITVIDPNREQUEST_VIDPN_MGR_____ = reinterpret_cast<decltype(___7COMMITVIDPNREQUEST_VIDPN_MGR__6B__SignedWithClassSignature_UCOMMITVIDPNREQUEST_VIDPN_MGR_____)>(0x0000000140095750); // 5369321296
