// RVA 0xAC6D0, .rdata
// Symbol: ?g_FeatureDependencyTables@@3QBUDXGK_FEATURE_DEPENDENCIES_CATEGORY_TABLE@@B
const struct DXGK_FEATURE_DEPENDENCIES_CATEGORY_TABLE near *const _g_FeatureDependencyTables__3QBUDXGK_FEATURE_DEPENDENCIES_CATEGORY_TABLE__B = reinterpret_cast<decltype(_g_FeatureDependencyTables__3QBUDXGK_FEATURE_DEPENDENCIES_CATEGORY_TABLE__B)>(0x00000001400ACD10); // 5369416976
