// RVA 0x1AED10, .rdata
// Symbol: ?Methods@?$IAttachableInputObjectSampleProxy_Receive@VBamoAttachableInputObjectSampleProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IAttachableInputObjectSampleProxy_Receive_VBamoAttachableInputObjectSampleProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IAttachableInputObjectSampleProxy_Receive_VBamoAttachableInputObjectSampleProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x00000001800ECE70); // 6443421296
