// RVA 0x1AED40, .rdata
// Symbol: ?Methods@?$IVirtualTouchpadControllerProxy_Receive@VBamoVirtualTouchpadControllerProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IVirtualTouchpadControllerProxy_Receive_VBamoVirtualTouchpadControllerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IVirtualTouchpadControllerProxy_Receive_VBamoVirtualTouchpadControllerProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x00000001800F0B20); // 6443436832
