// RVA 0x1AF020, .rdata
// Symbol: ?Methods@?$IControllerNavigationManagerPrincipal_Receive@VBamoControllerNavigationManagerPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IControllerNavigationManagerPrincipal_Receive_VBamoControllerNavigationManagerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IControllerNavigationManagerPrincipal_Receive_VBamoControllerNavigationManagerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x000000018011DEC0); // 6443622080
