// RVA 0x20949C, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUtzavUsrwUoryUlyquivUznwGEUkivxlnkOlyq@GazeHidParser
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUtzavUsrwUoryUlyquivUznwGEUkivxlnkOlyq_GazeHidParser = 0x00; // 0
