// RVA 0x710C8, .rdata
// Symbol: ??_7DMMVIDEOPRESENTTARGETSET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTTARGETSET@@@@@
void *___7DMMVIDEOPRESENTTARGETSET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGETSET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTTARGETSET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGETSET_____)>(0x00000001C0029180); // 7516361088
