// RVA 0x1F7618, .rdata
// Symbol: ??_7BamoList_ActivatableEntityPrincipal_StubImpl@ISMBamos_AutoBamos@BamoImpl@Lib@Bamo@Microsoft@@6B@
void *___7BamoList_ActivatableEntityPrincipal_StubImpl_ISMBamos_AutoBamos_BamoImpl_Lib_Bamo_Microsoft__6B_ = reinterpret_cast<decltype(___7BamoList_ActivatableEntityPrincipal_StubImpl_ISMBamos_AutoBamos_BamoImpl_Lib_Bamo_Microsoft__6B_)>(0x000000018002A340); // 6442623808
