// RVA 0x20C250, .rdata
// Symbol: ??_7BamoList_SimpleHapticsControllerFeedback_Principal@ISMBamos_AutoBamos@Lib@Bamo@Microsoft@@6BIList_SimpleHapticsControllerFeedback_Principal@1234@@
void *___7BamoList_SimpleHapticsControllerFeedback_Principal_ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BIList_SimpleHapticsControllerFeedback_Principal_1234__ = reinterpret_cast<decltype(___7BamoList_SimpleHapticsControllerFeedback_Principal_ISMBamos_AutoBamos_Lib_Bamo_Microsoft__6BIList_SimpleHapticsControllerFeedback_Principal_1234__)>(0x0000000180069D50); // 6442884432
