// RVA 0x202090, .rdata
// Symbol: ?Methods@?$IInputSystemInternalProxy_Receive@VBamoInputSystemInternalProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IInputSystemInternalProxy_Receive_VBamoInputSystemInternalProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IInputSystemInternalProxy_Receive_VBamoInputSystemInternalProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180133FE0); // 6443712480
