// RVA 0x2027A0, .rdata
// Symbol: ?Methods@?$ICUIComponentInputObjectProxy_Receive@VBamoCUIComponentInputObjectProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___ICUIComponentInputObjectProxy_Receive_VBamoCUIComponentInputObjectProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)(Microsoft::BamoImpl::BamoProxyImpl *this) = reinterpret_cast<decltype(_Methods___ICUIComponentInputObjectProxy_Receive_VBamoCUIComponentInputObjectProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180142540); // 6443771200
