// RVA 0x202D50, .rdata
// Symbol: ?Methods@?$IDeviceDockServerPrincipal_Receive@VBamoDeviceDockServerPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IDeviceDockServerPrincipal_Receive_VBamoDeviceDockServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IDeviceDockServerPrincipal_Receive_VBamoDeviceDockServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x000000018019ED40); // 6444150080
