// RVA 0x2696BC, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUwvorevibUhvieviUhbhgvnUlyquivUznwGEUkxsOlyq@InputDeliveryServer
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUwvorevibUhvieviUhbhgvnUlyquivUznwGEUkxsOlyq_InputDeliveryServer = 0x00; // 0
