// RVA 0x2696EC, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUhgbofhUzkrUhvieviUlyquivUznwGEUkivxlnkOlyq@PenDeviceServer
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUhgbofhUzkrUhvieviUlyquivUznwGEUkivxlnkOlyq_PenDeviceServer = 0x00; // 0
