// RVA 0x26967C, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUzggzxszyovrmkfglyqvxgUhbhgvnUerigfzoglfxskzwxlmgilooviUhvieviUlyquivUznwGEUkivxlnkOlyq@VirtualTouchpadControllerProxy
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUzggzxszyovrmkfglyqvxgUhbhgvnUerigfzoglfxskzwxlmgilooviUhvieviUlyquivUznwGEUkivxlnkOlyq_VirtualTouchpadControllerProxy = 0x00; // 0
