// RVA 0x269680, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUzggzxszyovrmkfglyqvxgUhbhgvnUdrmwldhnvhhztvwvorevibUhvieviUlyquivUznwGEUkivxlnkOlyq@WindowsMessageDeliveryProxy
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUzggzxszyovrmkfglyqvxgUhbhgvnUdrmwldhnvhhztvwvorevibUhvieviUlyquivUznwGEUkivxlnkOlyq_WindowsMessageDeliveryProxy = 0x00; // 0
