// RVA 0x2696D8, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgslhgUxlnklmvmghUnkxnzmztviUoryUlyquivUznwGEUkivxlnkOlyq@MPCManagerClient
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgslhgUxlnklmvmghUnkxnzmztviUoryUlyquivUznwGEUkivxlnkOlyq_MPCManagerClient = 0x00; // 0
