// RVA 0x269554, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUhbhgvnxlmgvcgUvmwklrmgUlyquivUznwGEUkxsOlyq@SystemContextEndpoint
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUhbhgvnxlmgvcgUvmwklrmgUlyquivUznwGEUkxsOlyq_SystemContextEndpoint = 0x00; // 0
