// RVA 0x1B44D0, .rdata
// Symbol: ??_7HomeGestureReadyChangedEventArgs@@6B?$ImplementsHelper@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00UIWeakReferenceSource@@@Details@WRL@Microsoft@@@
void *___7HomeGestureReadyChangedEventArgs__6B__ImplementsHelper_U__RuntimeClassFlags__00_WRL_Microsoft___00UIWeakReferenceSource___Details_WRL_Microsoft___ = reinterpret_cast<decltype(___7HomeGestureReadyChangedEventArgs__6B__ImplementsHelper_U__RuntimeClassFlags__00_WRL_Microsoft___00UIWeakReferenceSource___Details_WRL_Microsoft___)>(0x000000018004CB40); // 6442765120
