// RVA 0x1AFE10, .rdata
// Symbol: ?Methods@?$IResizeContextualProcessorPrincipal_Receive@VBamoResizeContextualProcessorPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IResizeContextualProcessorPrincipal_Receive_VBamoResizeContextualProcessorPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IResizeContextualProcessorPrincipal_Receive_VBamoResizeContextualProcessorPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x00000001800FD870); // 6443489392
