// RVA 0x1AF640, .rdata
// Symbol: ?Methods@?$IInputSiteManagerPrincipal_Receive@VBamoInputSiteManagerPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
_UNKNOWN *_Methods___IInputSiteManagerPrincipal_Receive_VBamoInputSiteManagerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B = reinterpret_cast<decltype(_Methods___IInputSiteManagerPrincipal_Receive_VBamoInputSiteManagerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180005D90); // 6442474896
