// RVA 0x1AFEF0, .rdata
// Symbol: ?Methods@?$IShellGesturesClientProxy_Receive@VBamoShellGesturesClientProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IShellGesturesClientProxy_Receive_VBamoShellGesturesClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IShellGesturesClientProxy_Receive_VBamoShellGesturesClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180101E30); // 6443507248
