// RVA 0x1AF660, .rdata
// Symbol: ?Methods@?$IInputSiteElementProxy_Receive@VBamoInputSiteElementProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
_UNKNOWN *_Methods___IInputSiteElementProxy_Receive_VBamoInputSiteElementProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B = reinterpret_cast<decltype(_Methods___IInputSiteElementProxy_Receive_VBamoInputSiteElementProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180011580); // 6442521984
