// RVA 0x20A3DC, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUfgrorgrvhUrmkfgxlmurtfizgrlmUlyquivUznwGEUkxsOlyq@InputConfiguration
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUfgrorgrvhUrmkfgxlmurtfizgrlmUlyquivUznwGEUkxsOlyq_InputConfiguration = 0x00; // 0
