// RVA 0x20A420, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUzggzxszyovrmkfglyqvxgUerigfzoglfxskzwxlmgilooviUhvieviUlyquivUznwGEUkivxlnkOlyq@VirtualTouchpadControllerProxy
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUzggzxszyovrmkfglyqvxgUerigfzoglfxskzwxlmgilooviUhvieviUlyquivUznwGEUkivxlnkOlyq_VirtualTouchpadControllerProxy = 0x00; // 0
