// RVA 0x23B030, .rdata
// Symbol: ??_7?$CSharedResourceMarshaler@VCCompositionAmbientLightMarshaler@DirectComposition@@$01@DirectComposition@@6B@
void *___7__CSharedResourceMarshaler_VCCompositionAmbientLightMarshaler_DirectComposition___01_DirectComposition__6B_ = reinterpret_cast<decltype(___7__CSharedResourceMarshaler_VCCompositionAmbientLightMarshaler_DirectComposition___01_DirectComposition__6B_)>(0x00000001C00C1FD0); // 7516987344
