// RVA 0x23FBF8, .rdata
// Symbol: ??_7?$CSharedResourceMarshaler@VCHolographicInteropTextureMarshaler@DirectComposition@@$01@DirectComposition@@6B@
void *___7__CSharedResourceMarshaler_VCHolographicInteropTextureMarshaler_DirectComposition___01_DirectComposition__6B_ = reinterpret_cast<decltype(___7__CSharedResourceMarshaler_VCHolographicInteropTextureMarshaler_DirectComposition___01_DirectComposition__6B_)>(0x00000001C00C9020); // 7517016096
