// RVA 0x293CBC, .data
// Symbol: ?gpfnHidP_GetUsages@@3V?$SGDRIMgpfnHidP_GetUsages@P6AJW4_HIDP_REPORT_TYPE@@GGPEAGPEAKPEAU_HIDP_PREPARSED_DATA@@PEADK@Z@@A
unsigned char _gpfnHidP_GetUsages__3V__SGDRIMgpfnHidP_GetUsages_P6AJW4_HIDP_REPORT_TYPE__GGPEAGPEAKPEAU_HIDP_PREPARSED_DATA__PEADK_Z__A = 0x00; // 0
