// RVA 0x190CD8, .data
// Symbol: ?gpfnHidP_GetLinkCollectionNodes@@3P6AJPEAU_HIDP_LINK_COLLECTION_NODE@@PEAKPEAU_HIDP_PREPARSED_DATA@@@ZEA
int (*_gpfnHidP_GetLinkCollectionNodes__3P6AJPEAU_HIDP_LINK_COLLECTION_NODE__PEAKPEAU_HIDP_PREPARSED_DATA___ZEA)(struct _HIDP_LINK_COLLECTION_NODE *, unsigned int *, struct _HIDP_PREPARSED_DATA *) = reinterpret_cast<decltype(_gpfnHidP_GetLinkCollectionNodes__3P6AJPEAU_HIDP_LINK_COLLECTION_NODE__PEAKPEAU_HIDP_PREPARSED_DATA___ZEA)>(0x0000000000000000); // 0
