// RVA 0x37880, .rdata
// Symbol: ??_7?$DoublyLinkedList@V?$AutoBuffer@U_DMM_VIDPNPATHANDTARGETMODESET_SERIALIZATION@@@DMM@@@@6B@
void *___7__DoublyLinkedList_V__AutoBuffer_U_DMM_VIDPNPATHANDTARGETMODESET_SERIALIZATION___DMM____6B_ = reinterpret_cast<decltype(___7__DoublyLinkedList_V__AutoBuffer_U_DMM_VIDPNPATHANDTARGETMODESET_SERIALIZATION___DMM____6B_)>(0x00000001C0002140); // 7516201280
