// RVA 0x37C40, .rdata
// Symbol: ??_7?$AutoBuffer@U_DMM_DISPMODECHANGEREQUESTSET_SERIALIZATION@@@DMM@@6BSetElement@@@
void *___7__AutoBuffer_U_DMM_DISPMODECHANGEREQUESTSET_SERIALIZATION___DMM__6BSetElement___ = reinterpret_cast<decltype(___7__AutoBuffer_U_DMM_DISPMODECHANGEREQUESTSET_SERIALIZATION___DMM__6BSetElement___)>(0x00000001C0032F20); // 7516401440
