// RVA 0x37C00, .rdata
// Symbol: ??_7?$AutoBuffer@U_DMM_VIDEOPRESENTTARGETSET_SERIALIZATION@@@DMM@@6BSetElement@@@
void *___7__AutoBuffer_U_DMM_VIDEOPRESENTTARGETSET_SERIALIZATION___DMM__6BSetElement___ = reinterpret_cast<decltype(___7__AutoBuffer_U_DMM_VIDEOPRESENTTARGETSET_SERIALIZATION___DMM__6BSetElement___)>(0x00000001C0032FE0); // 7516401632
