// RVA 0x89AC8, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwctnnhCUerwnnUxlivUlyquivUznwGEUkivxlnkOlyq@vidmm2
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwctnnhCUerwnnUxlivUlyquivUznwGEUkivxlnkOlyq_vidmm2 = 0x00; // 0
