// RVA 0x89B28, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwctnnhCUerwnnUkynnUpnlwvUlyquivUznwGEUkivxlnkOlyq@pbmm
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUxlivUwcpvimvoUwctpimoUwctnnhCUerwnnUkynnUpnlwvUlyquivUznwGEUkivxlnkOlyq_pbmm = 0x00; // 0
