// RVA 0x278610, .data
// Symbol: ?impl@?1??GetImpl@?$Feature@U__WilFeatureTraits_Feature_Servicing_DWMCrashesInBamoPrincipalImplLoop@@@wil@@CAAEAV?$FeatureImpl@U__WilFeatureTraits_Feature_Servicing_DWMCrashesInBamoPrincipalImplLoop@@@details@3@XZ@4V453@A
unsigned char _impl__1__GetImpl___Feature_U__WilFeatureTraits_Feature_Servicing_DWMCrashesInBamoPrincipalImplLoop___wil__CAAEAV__FeatureImpl_U__WilFeatureTraits_Feature_Servicing_DWMCrashesInBamoPrincipalImplLoop___details_3_XZ_4V453_A = 0x00; // 0
