// RVA 0x210530, .rdata
// Symbol: ?Interfaces@?$IList_TouchInjectionContact_Proxy_Receive@VBamoList_TouchInjectionContact_ProxyImpl@ISMBamos_AutoBamos@BamoImpl@Lib@Bamo@Microsoft@@@ISMBamos_AutoBamos@Lib@Bamo@Microsoft@@2QBUMsgCallInterfaceTableEntry@@B
unsigned char _Interfaces___IList_TouchInjectionContact_Proxy_Receive_VBamoList_TouchInjectionContact_ProxyImpl_ISMBamos_AutoBamos_BamoImpl_Lib_Bamo_Microsoft___ISMBamos_AutoBamos_Lib_Bamo_Microsoft__2QBUMsgCallInterfaceTableEntry__B = 0x67; // 103
