// RVA 0x20FE70, .rdata
// Symbol: ?Methods@?$IDeviceDockServerPrincipal_Receive@VBamoDeviceDockServerPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IDeviceDockServerPrincipal_Receive_VBamoDeviceDockServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IDeviceDockServerPrincipal_Receive_VBamoDeviceDockServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x00000001801ACD20); // 6444207392
