// RVA 0x20F970, .rdata
// Symbol: ?Methods@?$IWindowsMessageDeliveryProxy_Receive@VBamoWindowsMessageDeliveryProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IWindowsMessageDeliveryProxy_Receive_VBamoWindowsMessageDeliveryProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IWindowsMessageDeliveryProxy_Receive_VBamoWindowsMessageDeliveryProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x000000018001B660); // 6442563168
