// RVA 0x20EDE0, .rdata
// Symbol: ?Methods@?$ISystemContextEndpointPrincipal_Receive@VBamoSystemContextEndpointPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___ISystemContextEndpointPrincipal_Receive_VBamoSystemContextEndpointPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___ISystemContextEndpointPrincipal_Receive_VBamoSystemContextEndpointPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x000000018005AA40); // 6442822208
