// RVA 0x20FC90, .rdata
// Symbol: ?Methods@?$IInputAttemptedDeliveryClientProxy_Receive@VBamoInputAttemptedDeliveryClientProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IInputAttemptedDeliveryClientProxy_Receive_VBamoInputAttemptedDeliveryClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IInputAttemptedDeliveryClientProxy_Receive_VBamoInputAttemptedDeliveryClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180180D50); // 6444027216
