// RVA 0x278A98, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUortsgwrhnrhhUkilxvhhliUlyquivUznwGEUkxsOlyq@LightDismissProcessor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUortsgwrhnrhhUkilxvhhliUlyquivUznwGEUkxsOlyq_LightDismissProcessor = 0x00; // 0
