// RVA 0x278A68, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUzggzxszyovrmkfglyqvxgUhbhgvnUrmkfgwvovtzgrlmUhvieviUlyquivUznwGEUkivxlnkOlyq@InputDelegationInputObjectProxy
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlnklmvmghUzggzxszyovrmkfglyqvxgUhbhgvnUrmkfgwvovtzgrlmUhvieviUlyquivUznwGEUkivxlnkOlyq_InputDelegationInputObjectProxy = 0x00; // 0
