// RVA 0x278C2C, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUrmkfgulidziwviUhbhgvnUoryUlyquivUznwGEUkxsOlyq@InputForwardProcessor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUkilxvhhlihUrmkfgulidziwviUhbhgvnUoryUlyquivUznwGEUkxsOlyq_InputForwardProcessor = 0x00; // 0
