// RVA 0x278A7C, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUxlnklmvmghUrmkfgtvhgfivhUhbhgvnUlyquivUznwGEUkxsOlyq@GestureServices
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUxlmgvcgfzokilxvhhlihUxlnklmvmghUrmkfgtvhgfivhUhbhgvnUlyquivUznwGEUkxsOlyq_GestureServices = 0x00; // 0
