// RVA 0xF37B8, .rdata
// Symbol: ??_7?$RuntimeClass@U?$RuntimeClassFlags@$02@WRL@Microsoft@@UISpatialGraphNodePropertiesUpdatedCallback@Holographic@Internal@Windows@@VFtmBase@23@@WRL@Microsoft@@6B@
void *___7__RuntimeClass_U__RuntimeClassFlags__02_WRL_Microsoft__UISpatialGraphNodePropertiesUpdatedCallback_Holographic_Internal_Windows__VFtmBase_23__WRL_Microsoft__6B_ = reinterpret_cast<decltype(___7__RuntimeClass_U__RuntimeClassFlags__02_WRL_Microsoft__UISpatialGraphNodePropertiesUpdatedCallback_Holographic_Internal_Windows__VFtmBase_23__WRL_Microsoft__6B_)>(0x00000001800D9640); // 6443341376
