// RVA 0xF2D60, .rdata
// Symbol: ??_7?$RuntimeClass@U?$RuntimeClassFlags@$02@WRL@Microsoft@@UISpatialGraphNodeReference@Holographic@Internal@Windows@@VFtmBase@23@@WRL@Microsoft@@6BIInspectable@@@
void *___7__RuntimeClass_U__RuntimeClassFlags__02_WRL_Microsoft__UISpatialGraphNodeReference_Holographic_Internal_Windows__VFtmBase_23__WRL_Microsoft__6BIInspectable___ = reinterpret_cast<decltype(___7__RuntimeClass_U__RuntimeClassFlags__02_WRL_Microsoft__UISpatialGraphNodeReference_Holographic_Internal_Windows__VFtmBase_23__WRL_Microsoft__6BIInspectable___)>(0x00000001800C9730); // 6443276080
