// RVA 0xED238, .rdata
// Symbol: ??_7?$RuntimeClass@U?$RuntimeClassFlags@$01@WRL@Microsoft@@UIMessageProxyReconnectAdapterOwner@@UIMessageListListener@@UIViewHierarchy@@@WRL@Microsoft@@6B@
void *___7__RuntimeClass_U__RuntimeClassFlags__01_WRL_Microsoft__UIMessageProxyReconnectAdapterOwner__UIMessageListListener__UIViewHierarchy___WRL_Microsoft__6B_ = reinterpret_cast<decltype(___7__RuntimeClass_U__RuntimeClassFlags__01_WRL_Microsoft__UIMessageProxyReconnectAdapterOwner__UIMessageListListener__UIViewHierarchy___WRL_Microsoft__6B_)>(0x000000018002CF20); // 6442635040
