// RVA 0xEFAC0, .rdata
// Symbol: ??_7SpatialRimDeviceCollection@@6BISpatialInteractionSourceCollectionCallbacks@SpatialInteractions@Internal@Windows@@@
void *___7SpatialRimDeviceCollection__6BISpatialInteractionSourceCollectionCallbacks_SpatialInteractions_Internal_Windows___ = reinterpret_cast<decltype(___7SpatialRimDeviceCollection__6BISpatialInteractionSourceCollectionCallbacks_SpatialInteractions_Internal_Windows___)>(0x0000000180070520); // 6442911008
