// RVA 0x111DB2, .rdata
// Symbol: ?_TlgEvent@?5??StartActivity@CreateSpatialGraphNodeReference@HolographicDriverClientContinuousTrace@@QEAAXAEBU_GUID@@AEBUSPATIAL_NODE_ID@@W4SPATIAL_TRACKING_STATE@@@Z@4U_unnamed_type__TlgEvent_@?5??123@QEAAX012@Z@B
unsigned char __TlgEvent__5__StartActivity_CreateSpatialGraphNodeReference_HolographicDriverClientContinuousTrace__QEAAXAEBU_GUID__AEBUSPATIAL_NODE_ID__W4SPATIAL_TRACKING_STATE___Z_4U_unnamed_type__TlgEvent___5__123_QEAAX012_Z_B = 0x03; // 3
