// RVA 0xED680, .rdata
// Symbol: ?Methods@?$IControllerNavigationClientProxy_Receive@VBamoControllerNavigationClientProxyImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IControllerNavigationClientProxy_Receive_VBamoControllerNavigationClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IControllerNavigationClientProxy_Receive_VBamoControllerNavigationClientProxyImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180031870); // 6442653808
