// RVA 0xEC590, .rdata
// Symbol: ?Methods@?$IInputDeliveryServerPrincipal_Receive@VBamoInputDeliveryServerPrincipalImpl@BamoImpl@@@@2QBUMsgCallMethodDefinition@@B
__int64 (__fastcall *_Methods___IInputDeliveryServerPrincipal_Receive_VBamoInputDeliveryServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)() = reinterpret_cast<decltype(_Methods___IInputDeliveryServerPrincipal_Receive_VBamoInputDeliveryServerPrincipalImpl_BamoImpl____2QBUMsgCallMethodDefinition__B)>(0x0000000180023B60); // 6442597216
