// RVA 0x1360E8, .data
// Symbol: __@@_PchSym_@00@KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUnkxUoryUlyquivUznwGEUkivxlnkOlyq@MPCProcessor
unsigned char _____PchSym__00_KxulyqvxgPillgKxulmvxlivfzkUdrmwldhUnlwvimxlivUrmkfgeCUrmkfgkilxvhhlihUwverxvhUnkxUoryUlyquivUznwGEUkivxlnkOlyq_MPCProcessor = 0x00; // 0
