// RVA 0x8CCF8, .rdata
// Symbol: ??_7DMMVIDEOPRESENTSOURCESET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTSOURCESET@@@@@
void *___7DMMVIDEOPRESENTSOURCESET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTSOURCESET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTSOURCESET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTSOURCESET_____)>(0x00000001C0028BD0); // 7516359632
