// RVA 0x8CD30, .rdata
// Symbol: ??_7DMMVIDEOPRESENTTARGETSET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTTARGETSET@@@@@
void *___7DMMVIDEOPRESENTTARGETSET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGETSET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTTARGETSET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTTARGETSET_____)>(0x00000001C0028C00); // 7516359680
