// RVA 0x8CDF0, .rdata
// Symbol: ??_7DMMVIDEOPRESENTSOURCE@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTSOURCE@@@@@
void *___7DMMVIDEOPRESENTSOURCE__6B__SignedWithClassSignature_VDMMVIDEOPRESENTSOURCE_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTSOURCE__6B__SignedWithClassSignature_VDMMVIDEOPRESENTSOURCE_____)>(0x00000001C0028ED0); // 7516360400
