// RVA 0x8E6C8, .rdata
// Symbol: ??_7?$AutoBuffer@U_DMM_MONITORPRESENCEEVENTSET_SERIALIZATION@@@DMM@@6BSetElement@@@
void *___7__AutoBuffer_U_DMM_MONITORPRESENCEEVENTSET_SERIALIZATION___DMM__6BSetElement___ = reinterpret_cast<decltype(___7__AutoBuffer_U_DMM_MONITORPRESENCEEVENTSET_SERIALIZATION___DMM__6BSetElement___)>(0x00000001C00685C0); // 7516620224
