// RVA 0x24A378, .rdata
// Symbol: ??_7?$CSharedResourceMarshaler@VCCompositionDistantLightMarshaler@DirectComposition@@$01@DirectComposition@@6B@
void *___7__CSharedResourceMarshaler_VCCompositionDistantLightMarshaler_DirectComposition___01_DirectComposition__6B_ = reinterpret_cast<decltype(___7__CSharedResourceMarshaler_VCCompositionDistantLightMarshaler_DirectComposition___01_DirectComposition__6B_)>(0x000000014014A3A0); // 5370061728
