// RVA 0x9F870, .rdata
// Symbol: ?DestroyFlagsDefault@DXGDEVICE@@0U_D3DDDICB_DESTROYALLOCATION2FLAGS@@B
// Type: const struct _D3DDDI_SYNCHRONIZATIONOBJECT_FLAGS
unsigned char _DestroyFlagsDefault_DXGDEVICE__0U_D3DDDICB_DESTROYALLOCATION2FLAGS__B[0x4] = {};
