// RVA 0x8E560, .rdata
// Symbol: ?VmBusCommandTableVmToHost@DXG_HOST_GLOBAL_VMBUS@@2QBUDXG_VMBUS_COMMAND_TABLE@@B
const struct DXG_VMBUS_COMMAND_TABLE near *const _VmBusCommandTableVmToHost_DXG_HOST_GLOBAL_VMBUS__2QBUDXG_VMBUS_COMMAND_TABLE__B = reinterpret_cast<decltype(_VmBusCommandTableVmToHost_DXG_HOST_GLOBAL_VMBUS__2QBUDXG_VMBUS_COMMAND_TABLE__B)>(0x00000001C037B700); // 7519844096
