// RVA 0x66288, .rdata
// Symbol: ??_7DMMVIDEOPRESENTSOURCESET@@6B?$SignedWithClassSignature@VDMMVIDEOPRESENTSOURCESET@@@@@
void *___7DMMVIDEOPRESENTSOURCESET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTSOURCESET_____ = reinterpret_cast<decltype(___7DMMVIDEOPRESENTSOURCESET__6B__SignedWithClassSignature_VDMMVIDEOPRESENTSOURCESET_____)>(0x00000001C00255D0); // 7516345808
